<a href="https://colab.research.google.com/github/sreejas7919-bit/DSA_6/blob/main/numpy_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Activity
--------------
17-06-2026
----------

Question-1

Create a NumPy array with values from 10 to 49. Reshape into 4×10 matrix and extract last column.

Solution-1

import numpy as npImports the NumPy librarynp.arange(10,50)Creates an array from 10 to 49reshape(4,10)Converts the array into a 4×10 matrixmatrix[:, -1]Extracts the last columnprint()Displays the output

In [ ]:
import numpy as np

arr = np.arange(10, 50)
matrix = arr.reshape(4, 10)

print("Matrix:")
print(matrix)

print("\nLast Column:")
print(matrix[:, -1])

Matrix:
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

Last Column:
[19 29 39 49]


Question-2

Create two 3×3 matrices, add them, multiply element-wise, find transpose.

Solution-2

FunctionPurposeimport numpy as npImports the NumPy librarynp.full((3,3),5)Creates a 3×3 matrix filled with 5np.arange(1,10)Creates an array from 1 to 9reshape(3,3)Converts array into a 3×3 matrixA + BAdds two matricesA * BPerforms element-wise multiplication.TFinds the transpose of a matrixprint()Displays the output

In [ ]:
import numpy as np

# Matrix filled with 5s
A = np.full((3, 3), 5)

# Matrix with values 1 to 9
B = np.arange(1, 10).reshape(3, 3)

# Addition
add_result = A + B

# Element-wise multiplication
mul_result = A * B

# Transpose
transpose_result = mul_result.T

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition:")
print(add_result)

print("\nElement-wise Multiplication:")
print(mul_result)

print("\nTranspose:")
print(transpose_result)

Matrix A:
[[5 5 5]
 [5 5 5]
 [5 5 5]]

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Element-wise Multiplication:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose:
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


Question-3

3. Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.


Solution-3

FunctionPurposeimport numpy as npImports the NumPy librarynp.random.randint(10,101,15)Generates 15 random integers from 10 to 100arr > 50Checks values greater than 50np.sum(arr > 50)Counts values greater than 50arr[arr > 50] = -1Replaces values greater than 50 with -1print()Displays the output

In [ ]:
import numpy as np

# Create 15 random integers between 10 and 100
arr = np.random.randint(10, 101, 15)

print("Original Array:")
print(arr)

# Count values greater than 50
count = np.sum(arr > 50)

# Replace values greater than 50 with -1
arr[arr > 50] = -1

print("\nModified Array:")
print(arr)

print("\nNumber of values replaced:", count)

Original Array:
[93 50 97 74 49 83 66 54 74 11 52 93 36 51 23]

Modified Array:
[-1 50 -1 -1 49 -1 -1 -1 -1 11 -1 -1 36 -1 23]

Number of values replaced: 10


Question-4

4. Generate a 5×4 array with random values between 0 and 1 (float).
Find the row with the maximum sum of values.
● Normalize each row using the formula:

Normalized Row=row/sum of row

Solution-4

FunctionPurposeimport numpy as npImports the NumPy librarynp.random.rand(5,4)Creates a 5×4 array of random float valuesnp.sum(arr, axis=1)Calculates the sum of each rownp.argmax(row_sums)Finds the row with the maximum sumrow_sums[:, np.newaxis]Converts row sums into a column vectorarr / row_sums[:, np.newaxis]Normalizes each rowprint()Displays the output

In [ ]:
import numpy as np

# Generate 5x4 random float array
arr = np.random.rand(5, 4)

print("Original Array:")
print(arr)

# Sum of each row
row_sums = np.sum(arr, axis=1)

# Row with maximum sum
max_row = np.argmax(row_sums)

print("\nRow Sums:")
print(row_sums)

print("\nRow with Maximum Sum:", max_row)

# Normalize each row
normalized = arr / row_sums[:, np.newaxis]

print("\nNormalized Array:")
print(normalized)

Original Array:
[[0.0591693  0.29894272 0.07650514 0.06200132]
 [0.51297827 0.915377   0.19810419 0.34526304]
 [0.3968826  0.61133387 0.8783279  0.1336909 ]
 [0.67380008 0.00831261 0.3611528  0.52099233]
 [0.91697828 0.19840804 0.75168806 0.46666346]]

Row Sums:
[0.49661847 1.97172249 2.02023527 1.56425782 2.33373784]

Row with Maximum Sum: 4

Normalized Array:
[[0.11914438 0.6019565  0.15405214 0.12484698]
 [0.26016758 0.46425245 0.10047265 0.17510732]
 [0.19645365 0.30260529 0.43476516 0.0661759 ]
 [0.43074746 0.00531409 0.23087805 0.3330604 ]
 [0.39292257 0.08501728 0.32209619 0.19996396]]


Question-5

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

Solution-5

FunctionPurposeimport numpy as npImports the NumPy librarynp.array()Creates a NumPy arraynp.unique(arr)Finds unique elementsfor loopIterates through unique elementsnp.count_nonzero(arr == i)Counts occurrences of an elementduplicates.append(i)Adds duplicate elements to the listprint()Displays the output

In [ ]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

# Unique elements
unique_elements = np.unique(arr)

# Find duplicates
duplicates = []

for i in unique_elements:
    if np.count_nonzero(arr == i) > 1:
        duplicates.append(i)

print("Array:")
print(arr)

print("\nUnique Elements:")
print(unique_elements)

print("\nDuplicate Elements:")
print(duplicates)

Array:
[1 3 5 3 7 9 1 5 5]

Unique Elements:
[1 3 5 7 9]

Duplicate Elements:
[np.int64(1), np.int64(3), np.int64(5)]


Question-6

create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.

Solution-6

Function
-------Purpose
-------import numpy as npImports the NumPy librarynp.arange(1,37)Creates an array from 1 to 36reshape(6,6)Converts the array into a 6×6 matrixarr[1:5,1:5]Extracts the middle 4×4 submatrixsubmatrix % 2 == 0Checks for even numberssubmatrix[submatrix % 2 == 0]Extracts even numbersprint()Displays the output

In [ ]:
import numpy as np

# Create 6x6 array
arr = np.arange(1, 37).reshape(6, 6)

# Extract middle 4x4 submatrix
submatrix = arr[1:5, 1:5]

# Extract even numbers
even_numbers = submatrix[submatrix % 2 == 0]

print("Original Array:")
print(arr)

print("\nMiddle 4x4 Submatrix:")
print(submatrix)

print("\nEven Numbers:")
print(even_numbers)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even Numbers:
[ 8 10 14 16 20 22 26 28]
